<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260605152635 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE exercise (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE exercise_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, reps SMALLINT DEFAULT NULL, set SMALLINT DEFAULT NULL, weight SMALLINT DEFAULT NULL, scheduled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, start_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, end_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, exercise_id INT DEFAULT NULL, workout_session_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A512291E934951A ON exercise_session (exercise_id)');
        $this->addSql('CREATE INDEX IDX_A512291D1BA355 ON exercise_session (workout_session_id)');
        $this->addSql('CREATE TABLE workout (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE workout_exercise (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, workout_id INT DEFAULT NULL, exercise_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_76AB38AAA6CCCFC9 ON workout_exercise (workout_id)');
        $this->addSql('CREATE INDEX IDX_76AB38AAE934951A ON workout_exercise (exercise_id)');
        $this->addSql('CREATE TABLE workout_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, scheduled_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, workout_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AC82B97CA6CCCFC9 ON workout_session (workout_id)');
        $this->addSql('ALTER TABLE exercise_session ADD CONSTRAINT FK_A512291E934951A FOREIGN KEY (exercise_id) REFERENCES exercise (id)');
        $this->addSql('ALTER TABLE exercise_session ADD CONSTRAINT FK_A512291D1BA355 FOREIGN KEY (workout_session_id) REFERENCES workout_session (id)');
        $this->addSql('ALTER TABLE workout_exercise ADD CONSTRAINT FK_76AB38AAA6CCCFC9 FOREIGN KEY (workout_id) REFERENCES workout (id)');
        $this->addSql('ALTER TABLE workout_exercise ADD CONSTRAINT FK_76AB38AAE934951A FOREIGN KEY (exercise_id) REFERENCES exercise (id)');
        $this->addSql('ALTER TABLE workout_session ADD CONSTRAINT FK_AC82B97CA6CCCFC9 FOREIGN KEY (workout_id) REFERENCES workout (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE exercise_session DROP CONSTRAINT FK_A512291E934951A');
        $this->addSql('ALTER TABLE exercise_session DROP CONSTRAINT FK_A512291D1BA355');
        $this->addSql('ALTER TABLE workout_exercise DROP CONSTRAINT FK_76AB38AAA6CCCFC9');
        $this->addSql('ALTER TABLE workout_exercise DROP CONSTRAINT FK_76AB38AAE934951A');
        $this->addSql('ALTER TABLE workout_session DROP CONSTRAINT FK_AC82B97CA6CCCFC9');
        $this->addSql('DROP TABLE exercise');
        $this->addSql('DROP TABLE exercise_session');
        $this->addSql('DROP TABLE workout');
        $this->addSql('DROP TABLE workout_exercise');
        $this->addSql('DROP TABLE workout_session');
    }
}
